zoyasiddiqui/NoteNinja

- src/app/Main.java
- src/interface_adapter/edit_note/EditNotePresenter.java
- src/interface_adapter/search_notes/SearchViewModel.java
- src/view/SearchNotesView.java
I made some changes to how the homepage (SearchNotesView) starts up. It now begins maximazed and we have the button and title on the left.
Additionally, I set EditNotePresenter to update the note title each time we create a note so that the title is set to "untitled".
> GUI swing improvements for SearchNotesView

- src/view/EditNoteView.java
This modification adds a deleteNote button to the UI, initializes it, and adds an ActionListener for handling the button click event.
> Added DeleteNote Button

- src/interface_adapter/delete_note/DeleteNoteState.java
- src/interface_adapter/delete_note/DeleteNoteViewModel.java
Implement DeleteState and DeleteViewModel
- Add DeleteState class to manage state for note deletion.
- Implement DeleteViewModel with properties and methods for the delete view.
- Update relevant comments and documentation.
> Implemented DeleteNoteState and DeleteNoteViewModel

- src/app/Main.java
- src/app/SearchNotesUseCaseFactory.java
- src/data_access/EditNoteDataAccessObject.java
- src/use_case/delete_note/DeleteNoteDataAccessInterface.java
Changed the persistence to be done using the spreadsheet API
> Implement dao api

- src/interface_adapter/delete_note/DeleteNoteController.java
- src/interface_adapter/delete_note/DeleteNotePresenter.java
- src/use_case/delete_note/DeleteNoteInputBoundary.java
- src/use_case/delete_note/DeleteNoteInputData.java
- src/use_case/delete_note/DeleteNoteInteractor.java
- src/use_case/delete_note/DeleteNoteOutputBoundary.java
- src/use_case/delete_note/DeleteNoteOutputData.java
Added the Interactor for delete_note and implemented the methods from the input boundary. Also, set up input data class for delete_note.
> implemented InputData and Interactor

- src/entity/Note/CommonNote.java
- src/entity/Note/CommonNoteFactory.java
- src/entity/Note/Note.java
- src/entity/Note/NoteFactory.java
- src/use_case/create_note/CreateNoteInteractor.java
- src/use_case/delete_note/DeleteNoteOutputBoundary.java
- src/use_case/edit_note/EditNoteOutputData.java
minor bug fix, DeleteNoteOutputBoundary had an invalid import.
> design change note text

- src/data_access/EditNoteDataAccessObject.java
"Implementing note deletion functionality in EditNoteDataAccessObject"
This commit message succinctly describes the main purpose of the changes made in the commit. It indicates that the focus of the changes is on implementing the functionality related to deleting notes in the EditNoteDataAccessObject.
> Implemnting EditNoteDataAccessObject

- src/app/EditNoteUseCaseFactory.java
- src/app/Main.java
- src/app/SearchNotesUseCaseFactory.java
- src/data_access/EditNoteDataAccessObject.java
- src/interface_adapter/create_note/CreateNoteController.java
- src/interface_adapter/edit_note/EditNoteController.java
- src/interface_adapter/edit_note/EditNoteState.java
- src/interface_adapter/edit_note/EditNoteViewModel.java
- src/interface_adapter/save_note/SaveController.java
- src/interface_adapter/save_note/SavePresenter.java
- src/use_case/create_note/CreateNoteInputBoundary.java
- src/use_case/create_note/CreateNoteInteractor.java
- src/use_case/edit_note/EditNoteOutputData.java
- src/use_case/save_note/SaveNoteInteractor.java
- src/use_case/save_note/SaveNoteOutputBoundary.java
- src/view/EditNoteView.java
- src/view/SearchNotesView.java
Got the save button functioning. Still have yet to get the API functioning correctly.
> Save button

- src/data_access/EditNoteDataAccessObject.java
- src/interface_adapter/save_note/SaveController.java
- src/use_case/save_note/SaveNoteInputData.java
- src/use_case/search_notes/SearchNotesAccessInterface.java
- src/view/EditNoteView.java
Implemented SaveController's execute() method.  and also changed SearchNoteAccessInterface findByTag method to findByTitle and adjusted EditNoteDAO accordingly.
> Implemented SaveController's execute() method. 

- src/entity/Note/CommonNote.java
- src/entity/Note/CommonNoteFactory.java
- src/entity/Note/NoteFactory.java
- src/interface_adapter/create_note/CreateNoteController.java
- src/interface_adapter/edit_note/EditNotePresenter.java
- src/interface_adapter/edit_note/EditNoteViewModel.java
- src/use_case/create_AI_snippet/CreateAISnippetInteractor.java
- src/use_case/create_note/CreateNoteInputBoundary.java
- src/use_case/create_note/CreateNoteInputData.java
- src/use_case/create_note/CreateNoteInteractor.java
- src/use_case/delete_note/DeleteNoteInputData.java
- src/use_case/save_note/SaveNoteInteractor.java
- src/view/EditNoteView.java
Fixed several bugs that occurred after the previous pull request merge.
> Fixing AI snippet bugs

- README.md
- src/view/EditNoteView.java
> second test

- src/.gitignore
- src/data_access/CreateAISnippetDataAccessObject.java
Added .gitignore file in order to add file which holds api key and added functions to dao in order to access key
> Made the api key secure

- src/app/EditNoteUseCaseFactory.java
- src/entity/CodeSnippet/CodeSnippet.java
- src/entity/CodeSnippet/CommonCodeSnippet.java
- src/interface_adapter/create_code_snippet/CreateCodeSnippetController.java
- src/interface_adapter/create_code_snippet/CreateCodeSnippetPresenter.java
- src/interface_adapter/create_code_snippet/CreateCodeSnippetState.java
- src/interface_adapter/create_code_snippet/CreateCodeSnippetViewModel.java
- src/interface_adapter/edit_note/EditNotePresenter.java
- src/interface_adapter/edit_note/EditNoteViewModel.java
- src/use_case/create_code_snippet/CreateCodeSnippetDataAccessInterace.java
- src/use_case/create_code_snippet/CreateCodeSnippetDataAccessInterface.java
- src/use_case/create_code_snippet/CreateCodeSnippetInputBoundary.java
- src/use_case/create_code_snippet/CreateCodeSnippetInputData.java
- src/use_case/create_code_snippet/CreateCodeSnippetInteractor.java
- src/use_case/create_code_snippet/CreateCodeSnippetOutputBoundary.java
- src/use_case/create_code_snippet/CreateCodeSnippetOutputData.java
- src/use_case/edit_note/EditNoteOutputBoundary.java
- src/view/EditNoteView.java
Created interfaces and classes for handling code snippets, including CodeSnippet interface, CreateCodeSnippetInputBoundary, CreateCodeSnippetInteractor, CreateCodeSnippetOutputBoundary, CreateCodeSnippetOutputData, and CreateCodeSnippetController. Updated the presenter and view model to support code snippets. Also, added the corresponding data access interface for code snippets. Modified the use case creation method to support CodeSnippet functionality. The changes provide a structured framework for creating, executing, and presenting code snippets in the note-taking app."
> CodeSnippet Use Case Implementation

- src/.gitignore
- src/interface_adapter/create_AI_snippet/CreateAISnippetController.java
- src/use_case/create_AI_snippet/CreateAISnippetInputBoundary.java
- src/use_case/create_AI_snippet/CreateAISnippetInteractor.java
- src/view/EditNoteView.java
Implemented some bug fixes by changing AISnippet files
> Implemented some bug fixes by changing AISnippet files

- src/app/EditNoteUseCaseFactory.java
- src/data_access/CreateAISnippetDataAccessObject.java
- src/interface_adapter/create_AI_snippet/CreateAISnippetController.java
- src/interface_adapter/create_AI_snippet/CreateAISnippetPresenter.java
- src/use_case/create_AI_snippet/CreateAISnippetInputBoundary.java
- src/use_case/create_AI_snippet/CreateAISnippetInteractor.java
- src/view/EditNoteView.java
Fixed bugs for AISnippet in the files for interactor, presenter, and more.
> Fixing Bugs for AIsnippet

- src/view/EditNoteView.java
> testing a commit

- src/app/EditNoteUseCaseFactory.java
- src/app/Main.java
- src/data_access/CreateCodeSnippetDataAccessObject.java
- src/interface_adapter/create_code_snippet/CreateCodeSnippetController.java
- src/interface_adapter/edit_note/EditNotePresenter.java
- src/use_case/create_code_snippet/CreateCodeSnippetInputBoundary.java
- src/use_case/create_code_snippet/CreateCodeSnippetInputData.java
- src/use_case/create_code_snippet/CreateCodeSnippetInteractor.java
- src/use_case/delete_note/DeleteNoteInteractor.java
- src/use_case/edit_note/EditNoteOutputBoundary.java
- src/view/EditNoteView.java
remaining stuff to do:
- parsing of more complicated code strings
- properly retrieve a glot key from hidden place (right now its just entered as a string in the DAO)
unfortunately i was unable to get all of CodeSnippet usecase done right now as I found a lot of bugs to fix along the way. EditNoteUseCaseFactory was totally bugged and it took me some time to fix all the files.
> Implemented majority of CodeSnippet usecase

- src/local.properties
- src/main/java/data_access/CreateAISnippetDataAccessObject.java
- src/main/java/data_access/CreateCodeSnippetDataAccessObject.java
- src/main/java/use_case/create_AI_snippet/CreateAISnippetInteractor.java
Updated the AisnippetInteractor for better formatting and also updated the DAO's so it only exposes local src directory and not whole PC path.
> Updated Aisnippet Interactor, and DAOs file grab

- src/main/java/app/EditNoteUseCaseFactory.java
- src/main/java/app/Main.java
- src/main/java/data_access/CreateAISnippetDataAccessObject.java
- src/main/java/data_access/CreateCodeSnippetDataAccessObject.java
- src/main/java/use_case/create_code_snippet/CreateCodeSnippetInteractor.java
- src/main/java/view/EditNoteView.java
Fully Implemented CreateCodeSnippet use case finally.
Please go over it and adjust any bugs.
> Fully Implemented CreateCodeSnippet use case

- src/main/java/data_access/NoteDataAccessObject.java
- src/main/java/entity/Note/CommonNoteFactory.java
- src/main/java/use_case/create_code_snippet/CreateCodeSnippetInteractor.java
- src/main/java/use_case/save_note/SaveNoteInteractor.java
Implemented persistence of `NoteCount` value. Now, the system retains the count of created notes and assigns IDs accordingly. Two new methods, `getNoteCount()` and `incrementNoteCount()`, have been implemented to handle the incrementation of the integer value stored in `data.csv`.
Removed all `System.out.println()` debugging calls.
> Implemented NoteData persistence

- src/main/java/interface_adapter/create_code_snippet/CreateCodeSnippetController.java
- src/main/java/interface_adapter/delete_note/DeleteNoteController.java
- src/main/java/interface_adapter/edit_note/EditNoteViewModel.java
- src/main/java/interface_adapter/search_notes/SearchState.java
- src/test/java/entity/AISnippet/CommonAISnippetTest.java
- src/test/java/entity/CodeSnippet/CommonCodeSnippetTest.java
- src/test/java/entity/Note/CommonNoteFactoryTest.java
- src/test/java/entity/Note/CommonNoteTest.java
- src/test/java/interface_adapter/ViewManagerModelTest.java
- src/test/java/interface_adapter/ViewModelTest.java
- src/test/java/interface_adapter/create_AI_snippet/CreateAISnippetControllerTest.java
- src/test/java/interface_adapter/create_code_snippet/CreateCodeSnippetControllerTest.java
- src/test/java/interface_adapter/create_note/CreateNoteControllerTest.java
- src/test/java/interface_adapter/delete_note/DeleteNoteControllerTest.java
- src/test/java/interface_adapter/edit_note/EditNotePresenterTest.java
- src/test/java/interface_adapter/edit_note/EditNoteStateTest.java
- src/test/java/interface_adapter/edit_note/EditNoteViewModelTest.java
- src/test/java/interface_adapter/edit_note/RenameNoteControllerTest.java
- src/test/java/interface_adapter/save_note/SaveControllerTest.java
- src/test/java/interface_adapter/search_notes/SearchControllerTest.java
- src/test/java/interface_adapter/search_notes/SearchStateTest.java
- src/test/java/interface_adapter/search_notes/SearchViewModelTest.java
Implemented Testing for Entity directory and Interaface adapter
> Implemented Testing for Entity directory and Interaface adapter

- src/main/java/data_access/NoteDataAccessObject.java
- src/main/java/use_case/create_note/CreateNoteDataAccessInterface.java
- src/main/java/use_case/create_note/CreateNoteInteractor.java
- src/main/java/use_case/delete_note/DeleteNoteInteractor.java
- src/main/java/use_case/edit_note/EditNoteDataAccessInterface.java
- src/main/java/view/EditNoteView.java
Before this, our persistence layer was not actually working. I created two more csv files: one to store the number of notes being created and one to store all the notes. Now all of our functionality works as desired!
> Persistence

- src/main/java/app/EditNoteUseCaseFactory.java
- src/main/java/app/Main.java
fixed test case for EditNoteUseCaseFactoryTest, was crashing before
> fixed test case for EditNoteUseCaseFactoryTest, was crashing before

- src/main/java/app/EditNoteUseCaseFactory.java
- src/test/java/app/EditNoteUseCaseFactoryTest.java
- src/test/java/use_case/delete_note/DeleteNoteInteractorTest.java
Fixed testing issues and removed useless fix in source
> Fixed testing issues and removed useless fix in source

- src/test/java/use_case/save_note/SaveNoteInteractorTest.java
- src/test/java/use_case/search_notes/SearchInteractorTest.java
> Finished Testing for use_case
